# ===
# === Basics
# ===
[params]
favicon = '/favicon.png'
author = ''
keywords = []
description = ''

# ===
# === Header
# ===
[params.header]
logoText = 'Inkwell'
links = [
  { label = 'Archives', link = '/archives' },
  { label = 'Categories', link = '/categories' }
]

# ===
# === Article
# ===
[params.hero]
title = 'Inkwell demo'
subtitle = 'Welcome to Inkwell'

[params.hero.custom]
enableCustomButton = false
label = 'readmore'
link = '/about'

[params.article]
timeFormat = '2006-01-02'

[params.toc]
enableSmartTOC = true

[params.footer]
# Inkwell allow you to use icons from font awesome, before you have to make sure that there are font awesome in vendor
social = [
  { icon = 'fab fa-x-twitter', link = 'https://x.com/' },
  { icon = 'fab fa-github', link = 'https://github.com/' },
  { icon = 'fab fa-creative-commons', link = 'https://creativecommons.org/licenses/by-sa/4.0/' }
]

# ===
# === Vendor
# ===
# BEFORE YOU EDIT IT, PLEASE MAKE SURE THAT YOU KNOW WHAT YOU ARE DOING
# Register the required static resource files (including your custom ones) in the vendor block, Inkwell will
# automatically pull these resource files and render them
[params.vendor]
stylesheets = [
  'https://fonts.googleapis.com/css2?family=Literata:opsz,wght@7..72,400;7..72,700&family=Work+Sans:wght@900&family=Source+Code+Pro&display=swap',
  'https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css',
  'https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css',
  '/css/variables.css',
  '/css/inkwell.css'
]
scripts = [
  'https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js',
  'https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js',
  'https://kit.fontawesome.com/823a96a1b9.js',
  '/js/navbar.js',
  '/js/toc.js'
]
