# ===
# === Hugo Configure
# ===
# The absolute URL of your published site
baseURL = 'https://example.com/'

# Language code in html tag
languageCode = 'en-US'

# Site title
title = 'Example'

# Theme for whole site
theme = 'inkwell'

# Auto-detect Chinese / Japanese / Korean Languages in the content
hasCJKLanguage = true

# Content without language indicator will default to this language
defaultContentLanguage = 'en'

# Delete the hugo meta information from head
disableHugoGeneratorInject = true

# Articles per page
paginate = 8

# Summary length
summaryLength = 70

# Copyright which will be shown in the left of footer
copyright = 'Powered by <a href="https://github.com/scholar7r/Inkwell">Inkwell</a> & Hugo'

[taxonomies]
archive = 'archives'
category = 'categories'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'base16-snazzy'

# ===
# === Basics
# ===
[params]
favicon = '/favicon.png'
author = 'Your name'
keywords = ['Hugo', 'Inkwell']
description = 'A personal Hugo blog with Inkwell theme'

# ===
# === Header
# ===
[params.header]
logoText = 'Example'
links = [
  { label = 'Archives', link = '/archives' },
  { label = 'Categories', link = '/categories' }
]

# ===
# === Article
# ===
[params.hero]
title = 'Example'
subtitle = 'A personal Hugo blog with Inkwell theme'

[params.article]
timeFormat = '2006-01-02'

[params.toc]
enableToc = true

# ===
# === Comment
# ===
[params.giscus]
enableGiscus = false
repo=""
repoId=""
category="Announcements"
categoryId=""
mapping="pathname"
strict="0"
reactions="0"
emit="0"
inputPosition="top"
theme="light_tritanopia"
language="en-US"
loading="lazy"



[params.footer]
# Inkwell allow you to use icons from font awesome, before you have to make sure that there are font awesome in vendor
social = [
  { icon = 'fab fa-x-twitter', link = 'https://x.com/' },
  { icon = 'fab fa-github', link = 'https://github.com/' },
  { icon = 'fab fa-creative-commons', link = 'https://creativecommons.org/licenses/by-sa/4.0/' }
]

# ===
# === Vendor
# ===
# BEFORE YOU EDIT IT, PLEASE MAKE SURE THAT YOU KNOW WHAT YOU ARE DOING
# Register the required static resource files (including your custom ones) in the vendor block, Inkwell will
# automatically pull these resource files and render them
[params.vendor]
scripts = [
  'https://kit.fontawesome.com/823a96a1b9.js',
  '/js/navbar.js'
]
